### ISSUE TITLE
Error occurred when executing MoondreamQuery: size mismatch

### ISSUE THREAD

**Issue by DarkAlchy** [kijai/ComfyUI-moondream#18]
Error occurred when executing MoondreamQuery:

Error(s) in loading state_dict for Moondream:
size mismatch for vision_encoder.projection.mlp.fc1.weight: copying a param with shape torch.Size([8192, 2304]) from checkpoint, the shape in current model is torch.Size([8192, 1152]).
You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

Moondream2 has this issue, while moondream1 is fine.

What is broken?

**Comment by alenknight** [comment]
i'm having this issue too.  
![Screenshot 2024-06-17 at 1 55 59 AM](https://github.com/kijai/ComfyUI-moondream/assets/22153900/b9e2ebd5-78a0-4a3f-894a-8a2ddd2e1722)

**Comment by DarkAlchy** [comment]
I witched to the other node for moondream2 only and no issues.
